# Generated by Django 3.1.5 on 2021-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('order_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('gateway', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
            ],
        ),
    ]
